/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'jarvis' : IDL.Null,
});
export const Time = IDL.Int;
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const ReminderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'done' : IDL.Null,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReminderStatus,
  'title' : IDL.Text,
  'datetime' : Time,
});
export const Routine = IDL.Record({
  'name' : IDL.Text,
  'actions' : IDL.Vec(IDL.Text),
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([MessageRole, IDL.Text], [], []),
  'createNote' : IDL.Func([IDL.Text], [Note], []),
  'createReminder' : IDL.Func([IDL.Text, Time], [Reminder], []),
  'createRoutine' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [Routine], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
  'getConversation' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
  'getReminder' : IDL.Func([IDL.Nat], [Reminder], ['query']),
  'getRoutine' : IDL.Func([IDL.Text], [Routine], ['query']),
  'markReminderDone' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'webSearch' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MessageRole = IDL.Variant({ 'user' : IDL.Null, 'jarvis' : IDL.Null });
  const Time = IDL.Int;
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const ReminderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'done' : IDL.Null,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReminderStatus,
    'title' : IDL.Text,
    'datetime' : Time,
  });
  const Routine = IDL.Record({
    'name' : IDL.Text,
    'actions' : IDL.Vec(IDL.Text),
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([MessageRole, IDL.Text], [], []),
    'createNote' : IDL.Func([IDL.Text], [Note], []),
    'createReminder' : IDL.Func([IDL.Text, Time], [Reminder], []),
    'createRoutine' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [Routine], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
    'getConversation' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [Note], ['query']),
    'getReminder' : IDL.Func([IDL.Nat], [Reminder], ['query']),
    'getRoutine' : IDL.Func([IDL.Text], [Routine], ['query']),
    'markReminderDone' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'webSearch' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };