/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Time,
}
export type MessageRole = { 'user' : null } |
  { 'jarvis' : null };
export interface Note { 'id' : bigint, 'content' : string, 'timestamp' : Time }
export interface Reminder {
  'id' : bigint,
  'status' : ReminderStatus,
  'title' : string,
  'datetime' : Time,
}
export type ReminderStatus = { 'pending' : null } |
  { 'done' : null };
export interface Routine { 'name' : string, 'actions' : Array<string> }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addMessage' : ActorMethod<[MessageRole, string], undefined>,
  'createNote' : ActorMethod<[string], Note>,
  'createReminder' : ActorMethod<[string, Time], Reminder>,
  'createRoutine' : ActorMethod<[string, Array<string>], Routine>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllReminders' : ActorMethod<[], Array<Reminder>>,
  'getAllRoutines' : ActorMethod<[], Array<Routine>>,
  'getConversation' : ActorMethod<[], Array<Message>>,
  'getNote' : ActorMethod<[bigint], Note>,
  'getReminder' : ActorMethod<[bigint], Reminder>,
  'getRoutine' : ActorMethod<[string], Routine>,
  'markReminderDone' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'webSearch' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];